// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/CSMSettings.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text
{
    
    
    public final class CSMSettings
    {
        

        // The size, in pixels, for which the settings apply.
        public var fontSize: Number;
        
        // The inside cutoff value, above which densities are set to a maximum density value (such as 255).
        public var insideCutoff: Number;
        
        // The outside cutoff value, below which densities are set to zero.
        public var outsideCutoff: Number;
        

        
        public function CSMSettings(fontSize:Number, insideCutoff:Number, outsideCutoff:Number)
        {
            this.fontSize = fontSize;
            this.insideCutoff = insideCutoff;
            this.outsideCutoff = outsideCutoff;
        }
        
        
        
    }
}
