// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/H264VideoStreamSettings.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{
    
    public class H264VideoStreamSettings extends VideoStreamSettings
    {
        

        // [override] Video codec used for compression.
        private var _codec: String;
        
        // Level used for H.264/AVC encoding.
        private var _level: String;
        
        // Profile used for H.264/AVC encoding.
        private var _profile: String;
        

        
        public function H264VideoStreamSettings()
        {
            
        }
        
        
        

        // Set profile and level for video encoding.
        public function setProfileLevel(profile:String, level:String):void
        {
            // Unknown Implementation
        }

        public function get codec() : String
        {
            return this._codec;
        }
        

        public function get level() : String
        {
            return this._level;
        }
        

        public function get profile() : String
        {
            return this._profile;
        }
        
    }
}
