// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/IME.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{
    
    public final class IME extends EventDispatcher
    {
        

        // The conversion mode of the current IME.
        public var conversionMode: String;
        
        // Indicates whether the system IME is enabled (true) or disabled (false).
        public var enabled: Boolean;
        
        // The isSupported property is set to true if the IME class is available on the current platform, otherwise it is set to false.
        private var _isSupported: Boolean;
        

        
        
        

        // Causes the runtime to abandon any composition that is in progress.
        public static function compositionAbandoned():void
        {
            // Unknown Implementation
        }

        // Call this method when the selection within the composition has been updated, either interactively or programmatically.
        public static function compositionSelectionChanged(start:int, end:int):void
        {
            // Unknown Implementation
        }

        // Instructs the IME to select the first candidate for the current composition string.
        public static function doConversion():void
        {
            // Unknown Implementation
        }

        // Sets the IME composition string.
        public static function setCompositionString(composition:String):void
        {
            // Unknown Implementation
        }

        public function get isSupported() : Boolean
        {
            return this._isSupported;
        }
        
    }
}
