// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/MouseCursorData.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.ui
{
    
    import flash.geom.Point;
    
    
    public final class MouseCursorData
    {
        

        // A Vector of BitmapData objects containing the cursor image or images.
        public var data: Vector;
        
        // The frame rate for animating the cursor.
        public var frameRate: Number;
        
        // The hot spot of the cursor in pixels.
        public var hotSpot: Point;
        

        
        public function MouseCursorData()
        {
            
        }
        
        
        
    }
}
