// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/StyleSheet.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text
{
    
    public dynamic class StyleSheet extends EventDispatcher
    {
        

        // An array that contains the names (as strings) of all of the styles registered in this style sheet.
        private var _styleNames: Array;
        

        
        public function StyleSheet()
        {
            
        }
        
        
        

        // Removes all styles from the style sheet object.
        public function clear():void
        {
            // Unknown Implementation
        }

        // Returns a copy of the style object associated with the style named styleName.
        public function getStyle(styleName:String):Object
        {
            // Unknown Implementation
        }

        // Parses the CSS in CSSText and loads the style sheet with it.
        public function parseCSS(CSSText:String):void
        {
            // Unknown Implementation
        }

        // Adds a new style with the specified name to the style sheet object.
        public function setStyle(styleName:String, styleObject:Object):void
        {
            // Unknown Implementation
        }

        // Extends the CSS parsing capability.
        public function transform(formatObject:Object):flash.text:TextFormat
        {
            // Unknown Implementation
        }

        public function get styleNames() : Array
        {
            return this._styleNames;
        }
        
    }
}
