// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextRenderer.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text
{
    
    
    public final class TextRenderer
    {
        

        // Controls the rendering of advanced anti-aliased text.
        public var displayMode: String;
        
        // The adaptively sampled distance fields (ADFs) quality level for advanced anti-aliasing.
        public var maxLevel: int;
        

        
        
        

        // Sets a custom continuous stroke modulation (CSM) lookup table for a font.
        public static function setAdvancedAntiAliasingTable(fontName:String, fontStyle:String, colorType:String, advancedAntiAliasingTable:Array):void
        {
            // Unknown Implementation
        }
    }
}
