// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/URLRequestDefaults.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{
    
    
    public class URLRequestDefaults
    {
        

        // The default setting for the authenticate property of URLRequest objects.
        public var authenticate: Boolean;
        
        // The default setting for the cacheResponse property of URLRequest objects.
        public var cacheResponse: Boolean;
        
        // The default setting for the followRedirects property of URLRequest objects.
        public var followRedirects: Boolean;
        
        // The default setting for the idleTimeout property of URLRequest objects and HTMLLoader objects.
        public var idleTimeout: Number;
        
        // The default setting for the manageCookies property of URLRequest objects.
        public var manageCookies: Boolean;
        
        // The default setting for the useCache property of URLRequest objects.
        public var useCache: Boolean;
        
        // The default setting for the userAgent property of URLRequest objects.
        public var userAgent: String;
        

        
        
        

        // Sets default user and password credentials for a selected host.
        public static function setLoginCredentialsForHost(hostname:String, user:String, password:String):*
        {
            // Unknown Implementation
        }
    }
}
